#!/usr/bin/env python3

import argparse
from dedupe import FileCatalog, Source

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('source_dir', nargs='+',
                        help='A directory tree to be scanned.')

    a = parser.parse_args()
    f = FileCatalog(lambda entry: entry.get_digest())

    for i in range(len(a.source_dir)):
        Source(a.source_dir[i], i+1).walk(f)

    for k in sorted(set(f.store.keys())):
        print(k)

if __name__ == '__main__':
    exit(main())
